server:
  port: 5000
# 配置数据源
spring:
  datasource:
    forum:
      jdbc-url: jdbc:mysql://159.75.4.191:3306/forum_db
      username: root
      password: 1234
      # mysql驱动
      driver-class-name: com.mysql.jdbc.Driver
    bigdata:
      jdbc-url: jdbc:mysql://159.75.4.191:3306/deal_data
      username: root
      password: 1234
      # mysql驱动
      driver-class-name: com.mysql.jdbc.Driver

  # redis 配置
  redis:
#    url: redis://zheng:Abc123456@r-bp1ivsbptgt3l4feukpd.redis.rds.aliyuncs.com:6379
    # 114.222.230.84
    host: 159.75.4.191

    port: 6379

  jdbc:
    template:
      query-timeout: 5

mybatis:
  # mybatis 全局配置的值
  # 如果指定了mybatis的全局配置 , 就不能使用configuration的配置
#  config-location: classpath:mybatis/mybatis-config.xml
  # mybatis sql映射文件配置的值
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    # 驼峰映射关系
    map-underscore-to-camel-case: true

# 打印mybatis 产生的sql
logging:
  level:
    com.lucifer.springboot.cache.mapper: debug
