mysqlIp: 159.75.4.191
redisIp: 159.75.4.191

server:
  port: 5000
# 配置数据源
spring:
  # 定义swagger
  swagger:
    enabled: true # 生产环境中默认是不开启的

  datasource:
    forum:
      url: jdbc:mysql://${mysqlIp}:3306/forum_db
      username: root
      password: P!XcewfKwd85Xy0vXo+bbBFqerL3i&SWf~_0KL
      # mysql驱动 com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
#      druid:
#        # 下面为连接池的补充设置，应用到上面所有数据源中
#        # 初始化大小，最小，最大
#        initial-size: 5
#        min-idle: 5
#        max-active: 20
#        # 配置获取连接等待超时的时间
#        max-wait: 60000
#        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#        time-between-eviction-runs-millis: 60000
#        # 配置一个连接在池中最小生存的时间，单位是毫秒
#        min-evictable-idle-time-millis: 300000
#        #验证连接是否有效。此参数必须设置为非空字符串，下面三项设置成true才能生效
#        validationQuery: SELECT 1
#        #指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除.
#        testWhileIdle: true
#        #指明是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
#        testOnBorrow: true
#        #指明是否在归还到池中前进行检验
#        testOnReturn: false
    bigdata:
      url: jdbc:mysql://${mysqlIp}:3306/deal_data
      username: root
      password: P!XcewfKwd85Xy0vXo+bbBFqerL3i&SWf~_0KL
      # mysql驱动
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
#      druid:
#        # 下面为连接池的补充设置，应用到上面所有数据源中
#        # 初始化大小，最小，最大
#        initial-size: 5
#        min-idle: 5
#        max-active: 20
#        # 配置获取连接等待超时的时间
#        max-wait: 100000
#        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#        time-between-eviction-runs-millis: 60000
#        # 配置一个连接在池中最小生存的时间，单位是毫秒
#        min-evictable-idle-time-millis: 100000
#        #验证连接是否有效。此参数必须设置为非空字符串，下面三项设置成true才能生效
#        validationQuery: SELECT 1
#        #指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除.
#        testWhileIdle: true
#        #指明是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
#        testOnBorrow: true
#        #指明是否在归还到池中前进行检验
#        testOnReturn: false

  # redis 配置
  redis:
#    url: redis://zheng:Abc123456@r-bp1ivsbptgt3l4feukpd.redis.rds.aliyuncs.com:6379
    # 114.222.230.84
    host: ${redisIp}
    port: 6379
    password: eeBG5u4odHOe71ZXQLGtf4G1E+P+
    lettuce:
      pool:
        max-active: 8 # 连接池最大限制, 负数表示没有限制
        max-wait: -1ms # 连接池最大等待时间
        max-idle: 9 # 连接池最大空闲时间
    timeout: 500ms # 链接超时时间



  jdbc:
    template:
      query-timeout: 5

mybatis:
  # mybatis 全局配置的值
  # 如果指定了mybatis的全局配置 , 就不能使用configuration的配置
#  config-location: classpath:mybatis/mybatis-config.xml
  # mybatis sql映射文件配置的值
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    # 驼峰映射关系
    map-underscore-to-camel-case: true

#logging:
#  level:
#    com.dao.forum: debug # 打印mybatis 产生的sql

# 定义密钥
security:
  aes:
    iv: abcdefgabcdefg12
    key: abcdefgabcdefg12

realIpKey: X-real-ip
